logging:
  level: INFO
server:
  type: default
  applicationContextPath: /feed-subscriber
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001